### ISSUE TITLE
Offtiktok.com - "Woops... Something went wrong. Please try again"

### ISSUE THREAD

**Issue by engels74** [MarsHeer/offtiktok#4]
Hey

The offtiktok.com unfortunately seems to be completely broken. Using the "vm.offtiktok.com" option just leads you to the front page (offtiktok.com) and inputting the URL manually on the front page gives this error:
"Woops... Something went wrong. Please try again"

I hope you can fix it 🙂

**Comment by engels74** [comment]
Seems to have been solved now. Not sure if you did anything, but it works again

**Comment by StevenJonSmith** [comment]
It seems this bug is occuring again, unable to fetch videos to generate the link and adding off to a link manually just leads to the landing page.

**Comment by MarsHeer** [comment]
Commenting here for visibility, this should have been resolved
